# banner_img: https://w.wallhaven.cc/full/z8/wallhaven-z8wl1y.png

lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

index:
  slogan:
    enable: true
    text: YC 的小窝
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
  auto_excerpt:
    enable: true
  post_meta:
    date: true
    category: true
    tag: true

post:
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数
      enable: false
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Atom One Dark'
      bg_color: true
    prismjs:
      style: "default"
      preprocess: true

navbar:
  blog_title: YCSHome
  #  menu:
  #    - {
  #      key: '文档',
  #      icon: 'iconfont icon-books',
  #      submenu: [
  #        { key: '主题博客', link: 'https://hexo.fluid-dev.com/' },
  #        { key: '配置指南', link: 'https://hexo.fluid-dev.com/docs/guide/' },
  #        { key: '图标用法', link: 'https://hexo.fluid-dev.com/docs/icon/' }
  #      ]
  #    }

about:
  name: "YC"
  intro: "一个彩笔蒟蒻"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/YCSHome', tip: 'GitHub' }
